#!/bin/bash

# Use clang to build main.c, also building all other .c files in /src and
# including /src/headers in the include path. Output the executable to chip8

clang -O0 -g -o chip8_DBG src/*.c -I src/headers
